use crate::EmbeddedFile;

pub static SYSTEM_FILES: &[EmbeddedFile] = &[
    EmbeddedFile::text(
        "/sys/README.txt",
        include_str!("../../../assets/sys/README.txt"),
    ),
    EmbeddedFile::text(
        "/sys/apps/help.rhai",
        include_str!("../../../assets/sys/apps/help.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/pwd.rhai",
        include_str!("../../../assets/sys/apps/pwd.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/echo.rhai",
        include_str!("../../../assets/sys/apps/echo.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/ls.rhai",
        include_str!("../../../assets/sys/apps/ls.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/cat.rhai",
        include_str!("../../../assets/sys/apps/cat.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/mkdir.rhai",
        include_str!("../../../assets/sys/apps/mkdir.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/touch.rhai",
        include_str!("../../../assets/sys/apps/touch.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/rm.rhai",
        include_str!("../../../assets/sys/apps/rm.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/cp.rhai",
        include_str!("../../../assets/sys/apps/cp.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/mv.rhai",
        include_str!("../../../assets/sys/apps/mv.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/sysinfo.rhai",
        include_str!("../../../assets/sys/apps/sysinfo.rhai"),
    ),
    EmbeddedFile::text(
        "/sys/apps/hello.rhai",
        include_str!("../../../assets/sys/apps/hello.rhai"),
    ),
];
