use afos_api::{Error, Platform, Result};
use alloc::{string::String, vec::Vec};
use argon2::{Algorithm, Argon2, Params, Version};
use subtle::ConstantTimeEq;

use crate::Vfs;

const SECURITY_PATH: &str = "/user/config/security";
const SALT_LEN: usize = 16;
const HASH_LEN: usize = 32;

#[derive(Default)]
pub struct SecurityManager {
    failed_attempts: u32,
    blocked_until: u64,
}

impl SecurityManager {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            failed_attempts: 0,
            blocked_until: 0,
        }
    }

    pub fn has_password<P: Platform>(&mut self, vfs: &mut Vfs<P>) -> Result<bool> {
        vfs.exists(SECURITY_PATH)
    }

    pub fn set_password<P: Platform>(&mut self, vfs: &mut Vfs<P>, password: &str) -> Result<()> {
        if password.is_empty() {
            if vfs.exists(SECURITY_PATH)? {
                vfs.remove(SECURITY_PATH)?;
            }
            self.failed_attempts = 0;
            self.blocked_until = 0;
            return Ok(());
        }

        let mut salt = [0_u8; SALT_LEN];
        vfs.platform_mut().fill_random(&mut salt)?;
        let hash = derive(password.as_bytes(), &salt)?;
        let encoded = alloc::format!(
            "AFOS-AUTH-1\n{}\n{}\n",
            encode_hex(&salt),
            encode_hex(&hash)
        );
        vfs.write(SECURITY_PATH, encoded.as_bytes())?;
        self.failed_attempts = 0;
        self.blocked_until = 0;
        Ok(())
    }

    pub fn verify<P: Platform>(&mut self, vfs: &mut Vfs<P>, password: &str) -> Result<()> {
        let now = vfs.platform().monotonic_millis();
        if now < self.blocked_until {
            return Err(Error::RateLimited(self.blocked_until - now));
        }

        let encoded = vfs.read_text(SECURITY_PATH)?;
        let mut lines = encoded.lines();
        if lines.next() != Some("AFOS-AUTH-1") {
            return Err(Error::InvalidInput(String::from(
                "invalid security configuration",
            )));
        }
        let salt = decode_hex::<SALT_LEN>(
            lines
                .next()
                .ok_or_else(|| Error::InvalidInput(String::from("missing password salt")))?,
        )?;
        let expected = decode_hex::<HASH_LEN>(
            lines
                .next()
                .ok_or_else(|| Error::InvalidInput(String::from("missing password verifier")))?,
        )?;
        let actual = derive(password.as_bytes(), &salt)?;

        if bool::from(actual.ct_eq(&expected)) {
            self.failed_attempts = 0;
            self.blocked_until = 0;
            return Ok(());
        }

        self.failed_attempts = self.failed_attempts.saturating_add(1);
        if self.failed_attempts >= 3 {
            let exponent = (self.failed_attempts - 3).min(5);
            let delay = 1_000_u64 << exponent;
            self.blocked_until = now.saturating_add(delay);
        }
        Err(Error::AuthenticationFailed)
    }
}

fn derive(password: &[u8], salt: &[u8; SALT_LEN]) -> Result<[u8; HASH_LEN]> {
    // A single lane keeps behavior deterministic on every single-threaded backend.
    let params = Params::new(19 * 1024, 2, 1, Some(HASH_LEN))
        .map_err(|error| Error::Runtime(alloc::format!("Argon2 parameters: {error}")))?;
    let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let mut output = [0_u8; HASH_LEN];
    argon2
        .hash_password_into(password, salt, &mut output)
        .map_err(|error| Error::Runtime(alloc::format!("Argon2: {error}")))?;
    Ok(output)
}

fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = Vec::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(HEX[usize::from(byte >> 4)]);
        output.push(HEX[usize::from(byte & 0x0f)]);
    }
    // The generated bytes are always ASCII.
    String::from_utf8(output).unwrap_or_default()
}

fn decode_hex<const N: usize>(value: &str) -> Result<[u8; N]> {
    if value.len() != N * 2 {
        return Err(Error::InvalidInput(String::from(
            "invalid hexadecimal length",
        )));
    }
    let mut output = [0_u8; N];
    for (index, byte) in output.iter_mut().enumerate() {
        let high = hex_nibble(value.as_bytes()[index * 2])?;
        let low = hex_nibble(value.as_bytes()[index * 2 + 1])?;
        *byte = (high << 4) | low;
    }
    Ok(output)
}

fn hex_nibble(value: u8) -> Result<u8> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        b'A'..=b'F' => Ok(value - b'A' + 10),
        _ => Err(Error::InvalidInput(String::from(
            "invalid hexadecimal value",
        ))),
    }
}
