title: AFOS
description: A portable Rust application environment for desktop and UEFI
url: https://aspenini.github.io
baseurl: /AFOS
repository: Aspenini/AFOS
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - _site

